export const dashboardMenu = ([
  {
    title: "Workers",
    icon: "bx bx-user",
    path: "/workers",
    name: "workers",
    component: () => import("@/dashboard/views/workers.vue"),
    meta: { secure: true },
  },
  {
    title: "Dashboard",
    icon: "bx bx-bar-chart-alt-2",
    path: "/dashboard",
    name: "dashboard",
    component: () => import("@/dashboard/views/dashboard.vue"),
    meta: { secure: true },
  },
  {
    title: "Wallets",
    icon: "bx bx-wallet-alt",
    path: "/wallets",
    name: "wallets",
    component: () => import("@/dashboard/views/wallets.vue"),
    meta: { secure: true },
  },
  {
    title: "Daily report",
    icon: "bx bx-doughnut-chart",
    path: "/daily",
    name: "daily",
    component: () => import("@/dashboard/views/daily.vue"),
    meta: { secure: true },
  },
  {
    title: "Exchange",
    icon: "bx bx-slider-alt",
    path: "/exchange",
    name: "exchange",
    component: () => import("@/dashboard/views/exchange.vue"),
    meta: { secure: true },
  },
  {
    title: "Notifications",
    icon: "bx bx-bell",
    path: "/notifications",
    name: "notifications",
    component: () => import("@/dashboard/views/notifications.vue"),
    meta: { secure: true },
  },
]);
